# Generated by Django 3.0.7 on 2020-06-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20200621_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('accessories', 'accessories'), ('mobile', 'mobile'), ('notebook', 'notebook'), ('pc', 'pc')], default='mobile', max_length=20),
        ),
    ]
