# Generated by Django 3.0.7 on 2020-06-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20200621_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('notebook', 'notebook'), ('mobile', 'mobile'), ('accessories', 'accessories'), ('pc', 'pc')], default='mobile', max_length=20),
        ),
    ]
