# Generated by Django 3.0.7 on 2020-06-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20200624_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('сухие смеси и грунтовки', 'сухие смеси и грунтовки'), ('Листовые материалы', 'Листовые материалы'), ('Облицовочные материалы', 'Облицовочные материалы'), ('Изоляционные материалы', 'Изоляционные материалы')], default='сухие смеси и грунтовки', max_length=50),
        ),
    ]
