# Generated by Django 3.0.7 on 2020-06-25 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_auto_20200626_0212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product_id',
        ),
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('сухие смеси и грунтовки', 'сухие смеси и грунтовки'), ('Облицовочные материалы', 'Облицовочные материалы'), ('Изоляционные материалы', 'Изоляционные материалы'), ('Листовые материалы', 'Листовые материалы')], default='сухие смеси и грунтовки', max_length=50),
        ),
        migrations.CreateModel(
            name='CartEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.Product')),
            ],
        ),
    ]
