# Generated by Django 3.0.7 on 2020-06-26 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_auto_20200626_0229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartentry',
            options={'verbose_name': 'Товар в корзине', 'verbose_name_plural': 'Товары в корзине'},
        ),
        migrations.AlterField(
            model_name='cartentry',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Cart', verbose_name='Корзина'),
        ),
        migrations.AlterField(
            model_name='cartentry',
            name='count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='cartentry',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.Product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='pay',
            field=models.PositiveIntegerField(choices=[(1, 'Оплата картой'), (0, 'Наличные')], default=0, verbose_name='Тип оплаты'),
        ),
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('Облицовочные материалы', 'Облицовочные материалы'), ('Листовые материалы', 'Листовые материалы'), ('Изоляционные материалы', 'Изоляционные материалы'), ('сухие смеси и грунтовки', 'сухие смеси и грунтовки')], default='сухие смеси и грунтовки', max_length=50),
        ),
    ]
