# Generated by Django 3.0.7 on 2020-06-26 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_auto_20200626_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='pay',
            field=models.PositiveIntegerField(choices=[(1, 'Оплата картой'), (0, 'Наличные')], default=0, verbose_name='Тип оплаты'),
        ),
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('Облицовочные материалы', 'Облицовочные материалы'), ('Изоляционные материалы', 'Изоляционные материалы'), ('сухие смеси и грунтовки', 'сухие смеси и грунтовки'), ('Листовые материалы', 'Листовые материалы')], default='сухие смеси и грунтовки', max_length=50),
        ),
    ]
