# Generated by Django 3.0.7 on 2020-06-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_auto_20200626_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='pay',
            field=models.PositiveIntegerField(choices=[(0, 'Наличные'), (1, 'Оплата картой')], default=0, verbose_name='Тип оплаты'),
        ),
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('Облицовочные материалы', 'Облицовочные материалы'), ('сухие смеси и грунтовки', 'сухие смеси и грунтовки'), ('Изоляционные материалы', 'Изоляционные материалы'), ('Листовые материалы', 'Листовые материалы')], default='сухие смеси и грунтовки', max_length=50),
        ),
    ]
